// Generated by GitHub Copilot
import { NavLink, Navigate, Outlet, Route, Routes } from 'react-router-dom'
import { useEffect, useState } from 'react'
import './HealthcarePortal.css'

// Generated by GitHub Copilot
/**
 * Builds a fixed set of empty form rows for URL-encoded form submission.
 * @param {string[]} hints
 * @returns {Array<{ id: number, key: string, value: string }>}
 */
function createRows(hints) {
  return hints.map((hint, index) => ({
    id: Date.now() + index,
    key: hint,
    value: '',
  }))
}

// Generated by GitHub Copilot
/**
 * Converts form rows into a URLSearchParams payload for Spring model binding.
 * Empty keys are ignored to avoid sending invalid form fields.
 * @param {Array<{ key: string, value: string }>} rows
 * @returns {URLSearchParams}
 */
function buildFormPayload(rows) {
  const payload = new URLSearchParams()

  for (const row of rows) {
    const key = row.key.trim()
    if (key.length > 0) {
      payload.append(key, row.value)
    }
  }

  return payload
}

// Generated by GitHub Copilot
/**
 * Builds stable table columns from all object keys in a response list.
 * @param {Array<Record<string, unknown>>} items
 * @returns {string[]}
 */
function deriveColumns(items) {
  const keys = new Set()

  for (const item of items) {
    for (const key of Object.keys(item)) {
      keys.add(key)
    }
  }

  return Array.from(keys)
}

// Generated by GitHub Copilot
/**
 * Formats a table cell value including nested patient objects.
 * @param {unknown} value
 * @param {string} column
 * @returns {string}
 */
function formatCellValue(value, column) {
  if (value === null || value === undefined) {
    return ''
  }

  if (typeof value === 'object') {
    if (column === 'patient' && !Array.isArray(value)) {
      const patient = /** @type {Record<string, unknown>} */ (value)
      const patientParts = [
        patient.patientId ? `ID: ${String(patient.patientId)}` : '',
        patient.patientName ? `Name: ${String(patient.patientName)}` : '',
        patient.age ? `Age: ${String(patient.age)}` : '',
        patient.gender ? `Gender: ${String(patient.gender)}` : '',
        patient.contactNumber ? `Contact: ${String(patient.contactNumber)}` : '',
      ].filter(Boolean)

      return patientParts.join(' | ')
    }

    return JSON.stringify(value)
  }

  return String(value)
}

// Generated by GitHub Copilot
/**
 * Normalizes unknown request errors into a UI-safe message.
 * @param {unknown} error
 * @returns {string}
 */
function toFriendlyError(error) {
  if (error instanceof Error) {
    return error.message
  }

  return 'Unable to reach the server. Verify backend URL and try again.'
}

// Generated by GitHub Copilot
/**
 * Joins the configured backend base URL and controller path.
 * @param {string} baseUrl
 * @param {string} path
 * @returns {string}
 */
function buildEndpoint(baseUrl, path) {
  return `${baseUrl.trim().replace(/\/$/, '')}${path}`
}

// Generated by GitHub Copilot
/**
 * Reads a response body and returns a concise message for save operations.
 * @param {Response} response
 * @returns {Promise<string>}
 */
/**
 * Reads the response body once and returns a formatted message for success or error.
 * Handles Spring's BindingResult error arrays and plain string bodies.
 * @param {Response} response
 * @returns {Promise<string>}
 */
async function parseResponseBody(response) {
  const text = await response.text()

  if (!text) {
    return response.ok
      ? 'Saved successfully.'
      : `Error (${response.status}): No error message from server.`
  }

  try {
    const json = JSON.parse(text)

    if (Array.isArray(json)) {
      return json
        .map((err) => {
          if (typeof err === 'string') return err
          if (err.defaultMessage) return err.defaultMessage
          if (err.message) return err.message
          return JSON.stringify(err)
        })
        .join(' | ')
    }

    if (json.message) return json.message
    if (typeof json === 'string') return json

    return response.ok ? 'Saved successfully.' : JSON.stringify(json).substring(0, 200)
  } catch {
    return text.substring(0, 300)
  }
}

// Generated by GitHub Copilot
/**
 * Shared navigation shell for the healthcare frontend.
 * @returns {JSX.Element}
 */
function HealthcareLayout() {
  return (
    <div className="healthcare-shell">
      <header className="healthcare-header">
        <h1>Health Care App</h1>
        <nav className="main-nav" aria-label="Healthcare navigation">
          <NavLink to="/patients/add">Add Patient</NavLink>
          <NavLink to="/patients/list">Get Patients</NavLink>
          <NavLink to="/appointments/add">Add Appointment</NavLink>
          <NavLink to="/appointments/list">Get Appointments</NavLink>
        </nav>
      </header>

      <Outlet />
    </div>
  )
}

// Generated by GitHub Copilot
/**
 * Generic page for POSTing URL-encoded form fields to a Spring controller.
 * @param {{ title: string, endpoint: string, description: string, hints: string[] }} props
 * @returns {JSX.Element}
 */
function EntityFormPage({ title, endpoint, description, hints }) {
  const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8090'
  const [rows, setRows] = useState(() => createRows(hints))
  const [status, setStatus] = useState('')
  const [isSaving, setIsSaving] = useState(false)

  // Generated by GitHub Copilot
  /**
   * Updates the entered value for a fixed form field.
   * @param {number} id
   * @param {string} value
   */
  function updateRow(id, value) {
    setRows((current) =>
      current.map((row) => (row.id === id ? { ...row, value } : row)),
    )
  }

  // Generated by GitHub Copilot
  /**
   * Resets the form after a successful save.
   */
  function resetRows() {
    setRows(createRows(hints))
  }

  // Generated by GitHub Copilot
  /**
   * Sends the URL-encoded payload to the configured controller save endpoint.
   * @param {import('react').FormEvent<HTMLFormElement>} event
   */
  async function handleSubmit(event) {
    event.preventDefault()
    setIsSaving(true)
    setStatus('Saving...')

    try {
      const response = await fetch(buildEndpoint(baseUrl, endpoint), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
        },
        body: buildFormPayload(rows).toString(),
      })

      const bodyMessage = await parseResponseBody(response)
      if (!response.ok) {
        throw new Error(`Save failed: ${bodyMessage}`)
      }

      setStatus(bodyMessage || 'Saved successfully.')
      resetRows()
    } catch (error) {
      setStatus(toFriendlyError(error))
    } finally {
      setIsSaving(false)
    }
  }

  return (
    <section className="page-card" aria-labelledby={`${title}-heading`}>
      <div className="page-card__header">
        <h2 id={`${title}-heading`}>{title}</h2>
      </div>

      <form onSubmit={handleSubmit} className="entity-form">
        <div className="field-grid" role="group" aria-label={`${title} form fields`}>
          {rows.map((row, index) => (
            <div className="field-row" key={row.id}>
              <label htmlFor={`${title}-value-${row.id}`}>{row.key}</label>
              <input
                id={`${title}-value-${row.id}`}
                type="text"
                value={row.value}
                onChange={(event) => updateRow(row.id, event.target.value)}
                placeholder={`Enter ${row.key}`}
              />
            </div>
          ))}
        </div>

        <div className="form-footer">
          <button className="primary-btn" type="submit" disabled={isSaving}>
            Save
          </button>
          {status ? <p className="status-text" role="status">{status}</p> : null}
        </div>
      </form>
    </section>
  )
}

// Generated by GitHub Copilot
/**
 * Generic page for displaying a GET list endpoint in a table.
 * @param {{ title: string, endpoint: string, description: string, emptyMessage: string, hiddenColumns?: string[] }} props
 * @returns {JSX.Element}
 */
function EntityListPage({ title, endpoint, description, emptyMessage, hiddenColumns = [] }) {
  const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8090'
  const [items, setItems] = useState([])
  const [status, setStatus] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const columns = deriveColumns(items).filter((column) => !hiddenColumns.includes(column))

  // Generated by GitHub Copilot
  /**
   * Fetches the list endpoint and updates the table state.
   */
  async function fetchItems() {
    setIsLoading(true)
    setStatus('Loading...')

    try {
      const response = await fetch(buildEndpoint(baseUrl, endpoint))
      if (!response.ok) {
        throw new Error(`Request failed with status ${response.status}`)
      }

      const data = await response.json()
      setItems(Array.isArray(data) ? data : [])
      setStatus('Data loaded.')
    } catch (error) {
      setStatus(toFriendlyError(error))
    } finally {
      setIsLoading(false)
    }
  }

  useEffect(() => {
    fetchItems()
  }, [])

  return (
    <section className="page-card" aria-labelledby={`${title}-heading`}>
      <div className="list-header">
        <div>
          <h2 id={`${title}-heading`}>{title}</h2>
        </div>
        <button className="secondary-btn" type="button" onClick={fetchItems} disabled={isLoading}>
          Refresh
        </button>
      </div>

      {status ? <p className="status-text" role="status">{status}</p> : null}

      {items.length === 0 ? (
        <p className="empty-state">{emptyMessage}</p>
      ) : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                {columns.map((column) => (
                  <th key={column} scope="col">{column}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {items.map((item, rowIndex) => (
                <tr key={`${title}-${rowIndex}`}>
                  {columns.map((column) => (
                    <td key={`${rowIndex}-${column}`}>{formatCellValue(item[column], column)}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </section>
  )
}

// Generated by GitHub Copilot
/**
 * Dedicated add-patient form with fields matching PatientEntity:
 * patientName, age, gender, contactNumber.
 * patientId is auto-generated by the backend and is not included.
 * @returns {JSX.Element}
 */
function PatientFormPage() {
  const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8090'
  const initialForm = { patientName: '', age: '', gender: '', contactNumber: '' }
  const [form, setForm] = useState(initialForm)
  const [status, setStatus] = useState('')
  const [isSaving, setIsSaving] = useState(false)

  /**
   * Updates a single field in the patient form.
   * @param {string} field
   * @param {string} value
   */
  function updateForm(field, value) {
    setForm((current) => ({ ...current, [field]: value }))
  }

  /**
   * Submits the patient form as URL-encoded body to POST /patients/save.
   * @param {import('react').FormEvent<HTMLFormElement>} event
   */
  async function handleSubmit(event) {
    event.preventDefault()
    setIsSaving(true)
    setStatus('Saving...')

    try {
      const payload = new URLSearchParams()
      payload.append('patientName', form.patientName.trim())
      payload.append('age', form.age)
      payload.append('gender', form.gender.trim())
      payload.append('contactNumber', form.contactNumber.trim())

      const response = await fetch(buildEndpoint(baseUrl, '/patients/save'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },
        body: payload.toString(),
      })

      const bodyMessage = await parseResponseBody(response)
      if (!response.ok) {
        throw new Error(`Save failed: ${bodyMessage}`)
      }

      setStatus('Patient saved successfully.')
      setForm(initialForm)
    } catch (error) {
      setStatus(toFriendlyError(error))
    } finally {
      setIsSaving(false)
    }
  }

  return (
    <section className="page-card" aria-labelledby="add-patient-heading">
      <div className="page-card__header">
        <h2 id="add-patient-heading">Add Patient</h2>
      </div>

      <form onSubmit={handleSubmit} className="entity-form">
        <div className="fixed-field-grid">
          <div className="fixed-field-row">
            <label htmlFor="patientName">Patient Name</label>
            <input
              id="patientName"
              type="text"
              value={form.patientName}
              onChange={(e) => updateForm('patientName', e.target.value)}
              placeholder="Enter patient name"
              required
            />
          </div>

          <div className="fixed-field-row">
            <label htmlFor="age">Age</label>
            <input
              id="age"
              type="number"
              min="0"
              max="150"
              value={form.age}
              onChange={(e) => updateForm('age', e.target.value)}
              placeholder="Enter age"
              required
            />
          </div>

          <div className="fixed-field-row">
            <label htmlFor="gender">Gender</label>
            <select
              id="gender"
              value={form.gender}
              onChange={(e) => updateForm('gender', e.target.value)}
              required
            >
              <option value="">Select gender</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
              <option value="Other">Other</option>
            </select>
          </div>

          <div className="fixed-field-row">
            <label htmlFor="contactNumber">Contact Number</label>
            <input
              id="contactNumber"
              type="tel"
              value={form.contactNumber}
              onChange={(e) => updateForm('contactNumber', e.target.value)}
              placeholder="Enter contact number"
              required
            />
          </div>
        </div>

        <div className="form-footer">
          <button className="primary-btn" type="submit" disabled={isSaving}>
            Save Patient
          </button>
          {status ? <p className="status-text" role="status">{status}</p> : null}
        </div>
      </form>
    </section>
  )
}

// Generated by GitHub Copilot
/**
 * Dedicated add-appointment form with fields matching AppointmentBean.
 * appointmentId is auto-generated by the backend and is not included.
 * @returns {JSX.Element}
 */
function AppointmentFormPage() {
  const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8090'
  const initialForm = {
    appointmentDate: '',
    appointmentTime: '',
    doctorName: '',
    status: '',
    patientId: '',
  }
  const [form, setForm] = useState(initialForm)
  const [status, setStatus] = useState('')
  const [isSaving, setIsSaving] = useState(false)

  /**
   * Updates a single field in the appointment form.
   * @param {string} field
   * @param {string} value
   */
  function updateForm(field, value) {
    setForm((current) => ({ ...current, [field]: value }))
  }

  /**
   * Submits the appointment form as URL-encoded body to POST /appointments/save.
   * Uses patient.patientId so Spring can bind nested PatientBean.
   * @param {import('react').FormEvent<HTMLFormElement>} event
   */
  async function handleSubmit(event) {
    event.preventDefault()
    setIsSaving(true)
    setStatus('Saving...')

    try {
      const payload = new URLSearchParams()
      payload.append('appointmentDate', form.appointmentDate)
      payload.append('appointmentTime', form.appointmentTime)
      payload.append('doctorName', form.doctorName.trim())
      payload.append('status', form.status.trim())
      payload.append('patient.patientId', form.patientId)

      const response = await fetch(buildEndpoint(baseUrl, '/appointments/save'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },
        body: payload.toString(),
      })

      const bodyMessage = await parseResponseBody(response)
      if (!response.ok) {
        throw new Error(`Save failed: ${bodyMessage}`)
      }

      setStatus('Appointment saved successfully.')
      setForm(initialForm)
    } catch (error) {
      setStatus(toFriendlyError(error))
    } finally {
      setIsSaving(false)
    }
  }

  return (
    <section className="page-card" aria-labelledby="add-appointment-heading">
      <div className="page-card__header">
        <h2 id="add-appointment-heading">Add Appointment</h2>
      </div>

      <form onSubmit={handleSubmit} className="entity-form">
        <div className="fixed-field-grid">
          <div className="fixed-field-row">
            <label htmlFor="appointmentDate">Appointment Date</label>
            <input
              id="appointmentDate"
              type="date"
              value={form.appointmentDate}
              onChange={(e) => updateForm('appointmentDate', e.target.value)}
              required
            />
          </div>

          <div className="fixed-field-row">
            <label htmlFor="appointmentTime">Appointment Time</label>
            <input
              id="appointmentTime"
              type="time"
              value={form.appointmentTime}
              onChange={(e) => updateForm('appointmentTime', e.target.value)}
              required
            />
          </div>

          <div className="fixed-field-row">
            <label htmlFor="doctorName">Doctor Name</label>
            <input
              id="doctorName"
              type="text"
              value={form.doctorName}
              onChange={(e) => updateForm('doctorName', e.target.value)}
              placeholder="Enter doctor name"
              required
            />
          </div>

          <div className="fixed-field-row">
            <label htmlFor="appointmentStatus">Status</label>
            <input
              id="appointmentStatus"
              type="text"
              value={form.status}
              onChange={(e) => updateForm('status', e.target.value)}
              placeholder="Scheduled / Completed / Cancelled"
            />
          </div>

          <div className="fixed-field-row">
            <label htmlFor="patientId">Patient ID</label>
            <input
              id="patientId"
              type="number"
              min="1"
              value={form.patientId}
              onChange={(e) => updateForm('patientId', e.target.value)}
              placeholder="Existing patient ID"
              required
            />
          </div>
        </div>

        <div className="form-footer">
          <button className="primary-btn" type="submit" disabled={isSaving}>
            Save Appointment
          </button>
          {status ? <p className="status-text" role="status">{status}</p> : null}
        </div>
      </form>
    </section>
  )
}

// Generated by GitHub Copilot
/**
 * Defines the healthcare application routes.
 * @returns {JSX.Element}
 */
function HealthcarePortal() {
  return (
    <Routes>
      <Route element={<HealthcareLayout />}>
        <Route path="/patients/add" element={<PatientFormPage />} />
        <Route
          path="/patients/list"
          element={
            <EntityListPage
              title="Patient List"
              endpoint="/patients/list"
              description="GET /patients/list. Displays all patients returned by the backend."
              emptyMessage="No patients returned yet."
            />
          }
        />
        <Route
          path="/appointments/add"
          element={<AppointmentFormPage />}
        />
        <Route
          path="/appointments/list"
          element={
            <EntityListPage
              title="Appointment List"
              endpoint="/appointments/list"
              description="GET /appointments/list. Displays all appointments returned by the backend."
              emptyMessage="No appointments returned yet."
            />
          }
        />
      </Route>
      <Route path="*" element={<Navigate to="/patients/add" replace />} />
    </Routes>
  )
}

export default HealthcarePortal